---------------------------------------------
-- PROYECTO F3                             --
-- MODULO:PAE                              --
-- PROFESOR:LUIS ALONSO BOGANTES RODRIGUEZ --
-- ESTUDIANTE:JOSE JOAQUIN CAMPOS CHAVES   --
---------------------------------------------

-----------------------------------------
-- *** BORRAR LA BASE DE DATOS ***     --
-- DROP DATABASE FACTURACION_PANADERIA --
-----------------------------------------

-------------------------
-- CREAR BASE DE DATOS --
-------------------------

CREATE DATABASE FACTURACION_PANADERIA;
GO

---------------------------
-- USAR LA BASE DE DATOS --
---------------------------

USE FACTURACION_PANADERIA;
GO

------------------------
-- CREACION DE TABLAS --
------------------------

-- TABLA DE CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(9) UNIQUE NOT NULL   
);

-- TABLA DE VENDEDORES
CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(9) UNIQUE NOT NULL,    
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,    
);

-- TABLA DE PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    PRECIO DECIMAL(10, 2) CHECK (PRECIO >= 0) NOT NULL,
    STOCK INT CHECK (STOCK >= 0) NOT NULL
);

-- TABLA DE VENTAS
CREATE TABLE VENTAS (
    ID_VENTA INT PRIMARY KEY IDENTITY(1,1),
    METODOPAGO VARCHAR(50) DEFAULT 'Efectivo',
    FECHA DATE DEFAULT GETDATE(),
    ID_CLIENTE INT,	
    ID_VENDEDOR INT, 
    TOTAL DECIMAL(10, 2) CHECK (TOTAL >= 0) NOT NULL,
	ESTADO VARCHAR (20),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR),
	CONSTRAINT CHK_METODOPAGO
        CHECK (METODOPAGO IN ('Sinpe', 'Efectivo', 'Tarjeta'))
);

CREATE TABLE DETALLE_VENTAS (
    ID_VENTA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT CHECK (CANTIDAD >= 0) NOT NULL,
    PRECIO_VENTA DECIMAL(10, 2) CHECK (PRECIO_VENTA >= 0) NOT NULL,
    PRIMARY KEY (ID_VENTA, ID_PRODUCTO), -- Definir una llave primaria compuesta
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);


-- TABLA DE COMPRAS
CREATE TABLE COMPRAS (
    ID_COMPRA INT PRIMARY KEY IDENTITY(1,1),
    FECHA DATE DEFAULT GETDATE(),
    PROVEEDOR VARCHAR(100) NOT NULL,
    TOTAL DECIMAL(10, 2) CHECK (TOTAL >= 0) NOT NULL
);

-- TABLA DE DETALLE DE COMPRAS
CREATE TABLE DETALLE_COMPRAS (
    ID_DETALLE INT PRIMARY KEY IDENTITY(1,1),
    ID_COMPRA INT,
    NOMBRE VARCHAR(100),
    CANTIDAD INT CHECK (CANTIDAD >= 0) NOT NULL,    
    SUBTOTAL DECIMAL(10, 2) CHECK (SUBTOTAL >= 0) NOT NULL,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
    
);


----------------------
-- INGRESO DE DATOS --
----------------------

-- Insertar datos en la tabla CLIENTES
INSERT INTO CLIENTES (NOMBRE_COMPLETO, CEDULA) VALUES
('Cliente Default', '999999999'),
('Juan Perez', '111111111'),
('Ana Sanchez', '222222222'),
('Maria Rodriguez', '333333333'),
('Pedro Gomez', '444444444'),
('Luisa Fernandez', '555555555');

-- Insertar datos en la tabla VENDEDORES
INSERT INTO VENDEDORES (NOMBRE_COMPLETO, CEDULA, CORREO_ELECTRONICO) VALUES
('Carlos Gonzalez', '666666666', 'carlos@example.com'),
('Laura Martinez', '777777777', 'laura@example.com'),
('Marcos Ramirez', '888888888', 'javier@example.com'),
('Sofia Lopez', '123123123', 'sofia@example.com'),
('Roberto Herrera', '456456456', 'roberto@example.com');


-- Insertar datos en la tabla PRODUCTOS
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES
('Pan Integral', '100% Trigo', 1000, 10),
('Pan de Avena', 'Avena con pasas', 1010, 10),
('Croissant', 'Receta especial', 1020, 10),
('Rosquillas', 'Chocolate,Fresa,Vainilla', 1030, 10),
('Baguette', 'Tradicional', 1040, 10);


-- Insertar datos en la tabla VENTAS
INSERT INTO VENTAS (METODOPAGO, FECHA, ID_CLIENTE, ID_VENDEDOR, TOTAL, ESTADO) VALUES
('Tarjeta', '2023-09-01', 1, 1, 1000,'Pendiente'),
('Efectivo', '2023-09-02', 2, 2, 1010,'Pendiente'),
('Sinpe', '2023-09-03', 3, 3, 1020,'Pendiente'),
('Tarjeta', '2023-09-04', 4, 4, 1030,'Pendiente'),
('Efectivo', '2023-09-05', 5, 5, 1040,'Cancelada');


-- Insertar datos en la tabla DETALLE_VENTAS
INSERT INTO DETALLE_VENTAS (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_VENTA) VALUES
(1, 1, 1, 1000),
(2, 2, 1, 1010),
(3, 3, 1, 1020),
(4, 4, 1, 1030),
(5, 5, 1, 1040);


-- Insertar datos en la tabla COMPRAS
INSERT INTO COMPRAS (FECHA, PROVEEDOR, TOTAL) VALUES
('2023-09-01', 'Proveedor A', 500),
('2023-09-02', 'Proveedor B', 1000),
('2023-09-03', 'Proveedor C', 1500),
('2023-09-04', 'Proveedor D', 2000),
('2023-09-05', 'Proveedor E', 2500);


-- Insertar datos en la tabla DETALLE_COMPRAS
INSERT INTO DETALLE_COMPRAS (ID_COMPRA, NOMBRE, CANTIDAD, SUBTOTAL) VALUES
(1, 'Harina', 10, 1000),
(1, 'Sal', 5, 1000),
(2, 'Polvo de Hornear', 3, 1000),
(3, 'Aceite', 8, 1000),
(4, 'Huevos', 6, 1000);


SELECT * FROM CLIENTES
SELECT * FROM VENDEDORES
SELECT * FROM VENTAS
SELECT * FROM DETALLE_COMPRAS
SELECT * FROM COMPRAS
SELECT * FROM DETALLE_COMPRAS
SELECT * FROM PRODUCTOS


----------------------
-- STORE PROCEDURES --
----------------------

GO
CREATE OR ALTER PROCEDURE ELIMINAR_CLIENTE(@ID_CLIENTE INT, @MSJ VARCHAR(200) OUT)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTES WHERE ID_CLIENTE = @ID_CLIENTE)
    BEGIN
        SET @MSJ = 'EL CLIENTE NO EXISTE';
    END
    ELSE
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM VENTAS WHERE ID_CLIENTE = @ID_CLIENTE)
        BEGIN
            DELETE FROM CLIENTES WHERE ID_CLIENTE = @ID_CLIENTE;
            SET @MSJ = 'CLIENTE ELIMINADO';
        END
        ELSE
        BEGIN
            SET @MSJ = 'EL CLIENTE NO SE PUEDE ELIMINAR YA QUE TIENE VENTAS ASOCIADAS';
        END
    END
END
GO


CREATE OR ALTER PROCEDURE BUSCAR_CLIENTE(@ID_CLIENTE INT, @MSJ VARCHAR(200) OUT)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTES WHERE ID_CLIENTE = @ID_CLIENTE)
    BEGIN
        SET @MSJ = 'EL CLIENTE NO SE ENCUENTRA';
    END
    ELSE
    BEGIN
        SELECT ID_CLIENTE, NOMBRE_COMPLETO, CEDULA FROM CLIENTES
        WHERE ID_CLIENTE = @ID_CLIENTE;
        SET @MSJ = 'CLIENTE ENCONTRADO';
    END
END
GO


--CREATE OR ALTER PROCEDURE GUARDAR_CLIENTE(
--    @IDCLIENTE INT OUT,
--    @NOMBRE_COMPLETO VARCHAR(100),
--    @CEDULA VARCHAR(9),
--    @MSJ VARCHAR(200) OUT)
--AS
--BEGIN
--    IF @IDCLIENTE IS NULL
--    BEGIN
--        -- Insertar un nuevo cliente
--        INSERT INTO CLIENTES(NOMBRE_COMPLETO, CEDULA)
--        VALUES (@NOMBRE_COMPLETO, @CEDULA);    

--        SET @MSJ = 'CLIENTE INGRESADO';

--		SET @IDCLIENTE=IDENT_CURRENT('CLIENTES')

--    END
--    ELSE
--    BEGIN
--        -- Actualizar cliente existente
--        UPDATE CLIENTES
--        SET NOMBRE_COMPLETO = @NOMBRE_COMPLETO, CEDULA = @CEDULA
--        WHERE ID_CLIENTE = @IDCLIENTE;

--        SET @MSJ = 'CLIENTE MODIFICADO';
--    END
--END
--GO


--DECLARE @IDCLIENTE INT;
--DECLARE @MSJ VARCHAR(200);

---- Para insertar un nuevo cliente
--EXEC GUARDAR_CLIENTE @IDCLIENTE OUT, 'Jose Campos', '206730045', @MSJ OUT;

GO
CREATE OR ALTER PROCEDURE ELIMINAR_PRODUCTO(@ID_PRODUCTO INT, @MSJ VARCHAR(200) OUT)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
    BEGIN
        SET @MSJ = 'EL PRODUCTO NO EXISTE';
    END
    ELSE
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM DETALLE_VENTAS WHERE ID_PRODUCTO = @ID_PRODUCTO)
        BEGIN
            DELETE FROM PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO;
            SET @MSJ = 'PRODUCTO ELIMINADO';
        END
        ELSE
        BEGIN
            SET @MSJ = 'EL PRODUCTO NO SE PUEDE ELIMINAR YA QUE TIENE VENTAS ASOCIADAS';
        END
    END
END
GO


CREATE OR ALTER PROCEDURE ELIMINAR_VENDEDOR(@ID_VENDEDOR INT, @MSJ VARCHAR(200) OUT)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM VENDEDORES WHERE ID_VENDEDOR = @ID_VENDEDOR)
    BEGIN
        SET @MSJ = 'EL VENDEDOR NO EXISTE';
    END
    ELSE
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM VENTAS WHERE ID_VENDEDOR = @ID_VENDEDOR)
        BEGIN
            DELETE FROM VENDEDORES WHERE ID_VENDEDOR = @ID_VENDEDOR;
            SET @MSJ = 'VENDEDOR ELIMINADO';
        END
        ELSE
        BEGIN
            SET @MSJ = 'EL VENDEDOR NO SE PUEDE ELIMINAR YA QUE TIENE VENTAS ASOCIADAS';
        END
    END
END
GO


CREATE OR ALTER PROCEDURE GUARDAR_VENTA(
    @ID_VENTA INT OUT,
    @METODOPAGO VARCHAR(50),
    @FECHA DATE,
    @ID_CLIENTE INT,
    @ID_VENDEDOR INT,
    @TOTAL DECIMAL(10, 2),
    @ESTADO VARCHAR(20),
    @MSJ VARCHAR(200) OUT)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA)
    BEGIN
        -- Insertar una nueva venta
        INSERT INTO VENTAS(METODOPAGO, FECHA, ID_CLIENTE, ID_VENDEDOR, TOTAL, ESTADO)
        VALUES (@METODOPAGO, @FECHA, @ID_CLIENTE, @ID_VENDEDOR, @TOTAL, @ESTADO);

        SET @MSJ = 'VENTA INGRESADA';

        SET @ID_VENTA = IDENT_CURRENT('VENTAS');
    END
    ELSE
    BEGIN
        -- Actualizar venta existente
        IF EXISTS (SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA AND ESTADO = 'PENDIENTE')
        BEGIN
            UPDATE VENTAS
            SET METODOPAGO = @METODOPAGO, FECHA = @FECHA, ID_CLIENTE = @ID_CLIENTE, 
                ID_VENDEDOR = @ID_VENDEDOR, TOTAL = @TOTAL, ESTADO = @ESTADO
            WHERE ID_VENTA = @ID_VENTA;

            SET @MSJ = 'VENTA MODIFICADA';
        END
        ELSE
        BEGIN
            SET @MSJ = 'NO SE PUEDE MODIFICAR LA VENTA YA QUE NO ESTÁ PENDIENTE';
        END
    END
END
GO

CREATE OR ALTER PROCEDURE GUARDAR_DETALLE_VENTA(
    @ID_VENTA INT OUT,
    @ID_PRODUCTO INT,
    @CANTIDAD INT,
    @PRECIO_VENTA DECIMAL(10, 2),
    @MSJ VARCHAR(200) OUT)
AS
BEGIN
    DECLARE @EXISTENCIA INT
    DECLARE @DESCRIPCION VARCHAR(200)
    
    -- Verificar la existencia del producto
    SET @EXISTENCIA = (SELECT STOCK FROM PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
    
    IF NOT EXISTS (SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA)
    BEGIN
        SET @MSJ = 'NO SE PUEDE AGREGAR EL DETALLE YA QUE LA VENTA NO EXISTE'
    END
    ELSE
    BEGIN
        -- Verificar si la venta está en estado PENDIENTE
        IF EXISTS (SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA AND ESTADO = 'PENDIENTE')
        BEGIN
            IF (@EXISTENCIA < @CANTIDAD)
            BEGIN
                SET @MSJ = 'CANTIDAD INSUFICIENTE EN EL STOCK'
            END
            ELSE
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_VENTA AND ID_PRODUCTO = @ID_PRODUCTO)
                BEGIN
                    IF @CANTIDAD <= 0
                    BEGIN
                        SET @MSJ = 'LA CANTIDAD DE PRODUCTOS DEBE SER MAYOR A 0'
                    END
                    ELSE
                    BEGIN
                        -- Insertar el detalle de venta
                        INSERT INTO DETALLE_VENTAS(ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_VENTA)
                        VALUES (@ID_VENTA, @ID_PRODUCTO, @CANTIDAD, @PRECIO_VENTA)
                        SET @MSJ = 'DETALLE DE VENTA INGRESADO'
                    END
                END
                ELSE
                BEGIN
                    -- Actualizar el detalle de venta si ya existe
                    UPDATE DETALLE_VENTAS
                    SET CANTIDAD = @CANTIDAD, PRECIO_VENTA = @PRECIO_VENTA
                    WHERE ID_VENTA = @ID_VENTA AND ID_PRODUCTO = @ID_PRODUCTO
                    SET @DESCRIPCION = (SELECT NOMBRE FROM PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
                    SET @MSJ = 'DETALLE DE VENTA ACTUALIZADO PARA ' + @DESCRIPCION
                END
            END
        END
        ELSE
        BEGIN
            SET @MSJ = 'NO SE PUEDE MODIFICAR LA VENTA YA QUE NO ESTÁ EN ESTADO PENDIENTE'
        END
    END
END
GO

--SELECT ID_VENTA, METODOPAGO, FECHA, V.ID_CLIENTE, C.NOMBRE_COMPLETO, V.ID_VENDEDOR, VV.NOMBRE_COMPLETO, TOTAL, ESTADO
--FROM VENTAS V
--INNER JOIN CLIENTES C ON C.ID_CLIENTE = V.ID_CLIENTE
--INNER JOIN VENDEDORES VV ON VV.ID_VENDEDOR = V.ID_VENDEDOR;


--SELECT ID_VENTA,D.ID_PRODUCTO,NOMBRE,CANTIDAD,PRECIO_VENTA 
--FROM DETALLE_VENTAS D INNER JOIN PRODUCTOS P
--ON D.ID_PRODUCTO = P.ID_PRODUCTO

GO
CREATE OR ALTER PROCEDURE ELIMINAR_DETALLE_VENTA(@ID_VENTA INT, @ID_PRODUCTO INT, @MSJ VARCHAR(200) OUT)
AS
BEGIN
    BEGIN TRY
        IF NOT EXISTS(SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA)
        BEGIN
            SET @MSJ = 'LA VENTA NO EXISTE';
        END
        ELSE
        BEGIN
            IF EXISTS(SELECT 1 FROM VENTAS WHERE ID_VENTA = @ID_VENTA AND ESTADO = 'PENDIENTE')
            BEGIN
                BEGIN TRAN
                DELETE FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_VENTA AND ID_PRODUCTO = @ID_PRODUCTO;
                IF ((SELECT COUNT(ID_PRODUCTO) FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_VENTA) = 0)
                BEGIN
                    DELETE FROM VENTAS WHERE ID_VENTA = @ID_VENTA;
                    SET @MSJ = 'EL DETALLE Y LA VENTA FUERON ELIMINADOS';
                END
                ELSE
                BEGIN
                    SET @MSJ = 'DETALLE ELIMINADO';
                END
                COMMIT;
            END
            ELSE
            BEGIN
                SET @MSJ = 'LA VENTA NO SE PUEDE MODIFICAR YA QUE SE ENCUENTRA CANCELADA O ANULADA';
            END
        END
    END TRY
    BEGIN CATCH
        SET @MSJ = ERROR_MESSAGE();
        ROLLBACK TRAN;
    END CATCH
END;
GO

--------------
-- TRIGGERS --
--------------

GO
-- Este trigger se ejecutará después de insertar un nuevo registro en DETALLE_VENTAS y reducirá la cantidad de stock del producto correspondiente en la tabla PRODUCTOS.
CREATE OR ALTER TRIGGER TRIGGER_ACTUALIZAR_STOCK_VENTAS
ON DETALLE_VENTAS
AFTER INSERT, UPDATE , DELETE
AS
BEGIN
    -- Obtener el ID del producto y la cantidad vendida del registro insertado
    DECLARE @ID_PRODUCTO INT, @CANTIDAD INT;
    SELECT @ID_PRODUCTO = ID_PRODUCTO, @CANTIDAD = CANTIDAD
    FROM inserted;

    -- Actualizar el stock del producto en la tabla PRODUCTOS
    UPDATE PRODUCTOS
    SET STOCK = STOCK - @CANTIDAD
    WHERE ID_PRODUCTO = @ID_PRODUCTO;
END;
GO

-- Este trigger se ejecutará después de insertar o actualizar un registro en la tabla VENTAS y 
-- recalculará automáticamente el campo TOTAL basado en los SUBTOTAL de los registros en DETALLE_VENTAS asociados a esa venta.
GO
CREATE OR ALTER TRIGGER TRIGGER_CALCULAR_TOTAL_VENTA
ON VENTAS
AFTER INSERT, UPDATE
AS
BEGIN
    -- Obtener el ID de la venta del registro insertado o actualizado
    DECLARE @ID_VENTA INT;
    SELECT @ID_VENTA = ID_VENTA
    FROM inserted;

    -- Calcular el nuevo total de la venta
    UPDATE VENTAS
    SET TOTAL = ISNULL((SELECT SUM(PRECIO_VENTA) FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_VENTA), 0)
    WHERE ID_VENTA = @ID_VENTA;
END;
GO


-- Este trigger se ejecutará después de insertar o actualizar un registro en la tabla DETALLE_VENTAS
-- y recalculará automáticamente el campo TOTAL en la tabla VENTAS basado en los SUBTOTAL de los registros asociados a esa venta.
GO
CREATE OR ALTER TRIGGER TRIGGER_ACTUALIZAR_TOTAL_VENTA
ON DETALLE_VENTAS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    -- Obtener el ID de la venta del registro insertado, actualizado o eliminado
    DECLARE @ID_VENTA INT;
    SELECT @ID_VENTA = ID_VENTA
    FROM (SELECT ID_VENTA FROM inserted UNION SELECT ID_VENTA FROM deleted) AS VENTAS;

    -- Calcular el nuevo total de la venta
    UPDATE VENTAS
    SET TOTAL = ISNULL((SELECT SUM(PRECIO_VENTA) FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_VENTA), 0)
    WHERE ID_VENTA = @ID_VENTA;
END;
GO


GO
CREATE or ALTER TRIGGER TR_ACTUALIZA_INVENTARIO_BORRAR
ON DETALLE_VENTAS 
INSTEAD OF DELETE
AS
	DECLARE @ID_VENTA INT,
			@CODIGO_PRODUCTO INT, 
	        @CANTIDAD_VENDIDA INT,
			@EXISTENCIA INT

	SELECT @ID_VENTA = ID_VENTA FROM deleted
	SELECT @CODIGO_PRODUCTO = ID_PRODUCTO FROM deleted
	SELECT @CANTIDAD_VENDIDA = CANTIDAD FROM deleted
	
	SELECT @EXISTENCIA = (SELECT STOCK 
						  FROM PRODUCTOS P INNER JOIN deleted
						  ON P.ID_PRODUCTO = deleted.ID_PRODUCTO)
	UPDATE PRODUCTOS SET STOCK = @EXISTENCIA + @CANTIDAD_VENDIDA WHERE ID_PRODUCTO = @CODIGO_PRODUCTO  
	DELETE DETALLE_VENTAS WHERE ID_PRODUCTO = @CODIGO_PRODUCTO AND ID_VENTA =  @ID_VENTA

GO




