package Capa1_Presentacion;

import java.awt.Dimension;

public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState(frmMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuVendedores = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenuItem();
        mnuDetalle_Ventas = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClientes);

        mnuVendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuVendedores.setText("Vendedores");
        mnuVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendedoresActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVendedores);

        mnuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProductos);

        mnuVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuVentas.setText("Ventas");
        mnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVentas);

        mnuDetalle_Ventas.setText("Detalle Ventas");
        mnuDetalle_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetalle_VentasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDetalle_Ventas);

        mnuCompras.setText("Compras");
        mnuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCompras);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        frmClientes frm = new frmClientes();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeFrmClientes = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeFrmClientes.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeFrmClientes.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);

    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendedoresActionPerformed
       frmVendedores frm = new frmVendedores();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeFrmVendedores = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeFrmVendedores.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeFrmVendedores.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuVendedoresActionPerformed

    private void mnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasActionPerformed
         frmVentas frm = new frmVentas();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeFrmVentas = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeFrmVentas.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeFrmVentas.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuVentasActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        frmProductos frm = new frmProductos();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeFrmProductos = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeFrmProductos.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeFrmProductos.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuDetalle_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetalle_VentasActionPerformed
        frmDetalle_Ventas frm = new frmDetalle_Ventas();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeFrmDetalle_Ventas = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeFrmDetalle_Ventas.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeFrmDetalle_Ventas.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuDetalle_VentasActionPerformed

    private void mnuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprasActionPerformed
       frmCompras frm = new frmCompras();
        escritorio.add(frm);
        //entrar el formulario clientes
        //tamano de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamano de la ventana clientes
        Dimension sizeForm = frm.getSize();
        frm.setLocation(((int)sizeContenedor.getWidth()-(int)sizeForm.getWidth())/2,((int)sizeContenedor.getHeight()-(int)sizeForm.getHeight())/2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuCompras;
    private javax.swing.JMenuItem mnuDetalle_Ventas;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVendedores;
    private javax.swing.JMenuItem mnuVentas;
    // End of variables declaration//GEN-END:variables
}
